sudo: required
services:
 - docker

env:
  COMPOSE_VERSION: 1.8.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - sudo pip install tox

# setup databases
before_script:
 - cp conf/development.env.example conf/development.env
 - docker-compose build

script:
 - tox
 - docker-compose -f docker-compose-test.yml run --rm test bash bin/test_with_coverage -v2
 - docker-compose run --rm -e CABOT_SUPERUSER_USERNAME='admin' -e CABOT_SUPERUSER_PASSWORD='pass' web true

after_success:
  - pip install codecov
  - pip install django_coverage_plugin==1.3.1
  - codecov
