sudo: required
services:
 - docker

before_install:
 - sudo pip install tox

# setup databases
before_script:
 - cp conf/development.env.example conf/development.env
 - docker-compose build

script:
 - tox
 - docker-compose -f docker-compose-test.yml run --rm --entrypoint bin/test_with_coverage test -v2
 - git checkout $(git describe --abbrev=0 --tags `git describe --tags`^) && docker-compose build web
 - docker-compose run --rm web true
 - git checkout - && docker-compose build web
 - docker-compose run --rm web true

after_success:
  - sudo pip install codecov
  - sudo pip install django_coverage_plugin==1.4.2
  - codecov
