sudo: required
services:
 - docker

env:
 global:
  - AUTH_LDAP=true
  - COMPOSE_VERSION=1.8.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

# setup databases
before_script:
 - cp conf/development.env.example conf/development.env
 - docker-compose build
 - docker-compose up -d
 - sleep 20

script:
 - docker-compose run web python manage.py test cabot
