version: '2'
services:
  web:
    env_file:
     - conf/development.env
    build: .
    image: cabot:web
    command: python manage.py runserver 0.0.0.0:5001
    ports:
     - "5001:5001"
    volumes:
     - .:/code
    links:
     - rabbitmq
     - db_psql
     - db_mysql

  worker:
    env_file:
     - conf/development.env
    image: cabot:web
    command: bash -euc "dockerize -wait tcp://db_psql:5432 -timeout 60s; dockerize -wait tcp://root:test@db_mysql:3306 -timeout 60s; python manage.py celery worker -B -A cabot --loglevel=DEBUG --concurrency=16 --logfile=/var/log/cabot-celery.log -Ofair"
    volumes:
     - .:/code
    links:
     - rabbitmq
     - db_psql
     - db_mysql
    depends_on:
     - db_psql
     - db_mysql
     - rabbitmq

  rabbitmq:
    image: rabbitmq

  db_psql:
    image: postgres

  db_mysql:
    image: mysql-5.6
    environment:
      - MYSQL_ROOT_PASSWORD=test

  wait_psql:
    image: cabot:web
    command: dockerize -wait tcp://db_psql:5432 -timeout 60s
    depends_on:
      - db_psql

  wait_mysql:
    image: cabot:web
    command: dockerize -wait tcp://root:test@db_mysql:3306 -timeout 60s
    depends_on:
      - db_mysql
