version: '2'
services:
  web:
    env_file:
     - conf/development.env
    build: .
    image: cabot:web
    command: python manage.py runserver 0.0.0.0:5001
    ports:
     - "5001:5001"
    volumes:
     - .:/code
    links:
     - redis
     - db

  worker:
    env_file:
     - conf/development.env
    image: cabot:web
    command: python manage.py celery worker -A cabot --loglevel=DEBUG --concurrency=16 -Ofair
    volumes:
     - .:/code
    links:
     - redis
     - db

  beat:
    env_file:
     - conf/development.env
    image: cabot:web
    command: python manage.py celery beat -A cabot --loglevel=DEBUG
    volumes:
     - .:/code
    links:
     - redis
     - db

  redis:
    image: redis

  db:
    image: postgres
