version: '2'
services:
  web:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    environment:
      - CABOT_SUPERUSER_USERNAME=admin
      - CABOT_SUPERUSER_PASSWORD=pass
    command: python manage.py runserver 0.0.0.0:5001
    ports:
      - "5000:5000"
    links:
      - redis
      - db

  worker:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    command: python manage.py celery worker -A cabot --loglevel=DEBUG --concurrency=16 -Ofair
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    links:
      - redis
      - db

  beat:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    command: python manage.py celery beat -A cabot --loglevel=DEBUG
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    links:
      - redis
      - db

  redis:
    image: redis

  db:
    image: postgres
